services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    ports:
      - "5433:5432"   # optional (handy for local inspection)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d events"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
      POSTGRES_DSN: "postgres://postgres:postgres@db:5432/events?sslmode=disable"
      QUEUE_MAX_SIZE: "10000"
      BATCH_MAX_SIZE: "500"
      BATCH_MAX_WAIT_MS: "50"
      MAX_BODY_BYTES: "1048576"
      RATE_LIMIT_METRICS_PER_MIN: "20"
      API_KEYS: ""             # set to "mykey" to require an API key
      CLOCK_SKEW_SECONDS: "300"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pg_data:
